# Generated by Django 5.0.6 on 2024-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Subscription', 'Subscription')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Subscription', 'Subscription'), ('Payment', 'Payment'), ('Promotion', 'Promotion')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('recipient', models.EmailField(max_length=254)),
                ('date_sent', models.DateTimeField()),
                ('details', models.TextField()),
            ],
        ),
    ]
