# Generated by Django 5.0.6 on 2024-06-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='subject',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Subscription', 'Subscription'), ('Discount', 'Discount')], default='NULL', max_length=50),
        ),
    ]
